### ISSUE TITLE
Error while trying to install using ROCm option

### ISSUE THREAD

**Issue by quaintdev** [ddh0/easy-llama#1]
I am on Fedora 40 and installed rocm and hip from fedora repositories. I keep getting below error while trying to run 

`CC=/usr/lib64/llvm17/bin/clang CXX=/usr/lib64/llvm17/bin/clang++ CMAKE_ARGS="-DLLAMA_HIPBLAS=1 -DLLAMA_FAST=1" pip install --no-cache-dir llama-cpp-python`

Note that I had to set CC and CXX variables as per my installation in above command. I get below error when I run it.

```
     CMake Error at vendor/llama.cpp/CMakeLists.txt:556 (find_package):
        By not providing "Findhip.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "hip", but
        CMake did not find one.

        Could not find a package configuration file provided by "hip" with any of
        the following names:

          hipConfig.cmake
          hip-config.cmake

        Add the installation prefix of "hip" to CMAKE_PREFIX_PATH or set "hip_DIR"
        to a directory containing one of the above files.  If "hip" provides a
        separate development package or SDK, be sure it has been installed.


      -- Configuring incomplete, errors occurred!

      *** CMake configuration failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects
```

Any help would be highly appreciated. Thanks!

**Comment by ddh0** [comment]
A little bit of digging and I found [this comment](https://github.com/ROCm/HIP/issues/955#issuecomment-471863747) which says you'll need to set the CMAKE_MODULE_PATH variable. See [here](https://github.com/ROCm-Developer-Tools/HIP/tree/master/samples/2_Cookbook/12_cmake_hip_add_executable#including-findhip-cmake-module-in-the-project) for more details.

If this doesn't work, could you see if cmake is available in Fedora's package manager, and try installing that way?
