### ISSUE TITLE
Python 3.10 ImportError: cannot import name 'UTC' from 'datetime' 

### ISSUE THREAD

**Issue by iwr-redmond** [ddh0/easy-llama#6]
[webui.py#L25](https://github.com/ddh0/easy-llama/blob/cdacf875dd2821d75fe4f1e919c49d4ec2469c48/easy_llama/webui.py#L25) causes an import error on Python 3.10:

This causes an import error when attempting to import easy_llama on Python 3.10:

```
ImportError: cannot import name 'UTC' from 'datetime' (C:\Program Files\Python310\lib\datetime.py) (Windows)
ImportError: cannot import name 'UTC' from 'datetime' (/usr/lib/python3.10/datetime.py) (Ubuntu 22.04)
```

Per [OpenWebUI discussion 4951](https://github.com/open-webui/open-webui/discussions/4951), a quick fix is to change the code to:

```
from datetime import datetime, timedelta, timezone
UTC = timezone.utc
```

**Comment by ddh0** [comment]
Hey, thanks for letting me know. This is now fixed in release 0.1.109.
